# the amazon sdk has a config.inc.php file. This files is
# a copy of that file and will insert these values when and
# where needed.

# You should put other settings in your app.yml file 


aws_key: 1234
aws_secret_key: 12345
aws_account_id: 123
aws_canonical_id: 123
aws_canonical_name: name
aws_mfa_serial: 123456789012
aws_cloudfront_leypair_id: 123
aws_private_key_pem: "contains the contents of pem file"
aws_enable_extensions: false


